
import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "../components/NavBar"


const inter = Inter({ subsets: ["latin"] });

 export const metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
 };

export default function RootLayout({ children }) {
  
  return (
    <html lang="es">
      <body className={inter.className}>
        <div className="flex flex-col md:flex-row w-screen justify-between">
          <div className="md:min-w-80">
          <NavBar/>
          </div>
          {children}
          {
            /* hacerle lo mismo que al nav.  */
          }
          <div className="min-w-80 border-l-2 my-10 p-10 hidden xl:block">
            <h2>En esta sección</h2>
            <p>- Botones</p>
            <p>- Descripción</p>
            <p>- Vista de componentes</p>
            <p>- Boton uno</p>
            <p>- Boton dos</p>
            <p>- Boton tres</p>
            <p>- Boton cuatro</p>

          </div>
        </div>
      </body>
    </html>
  );
}
